-- Aplicação-alvo do TCC
-- Execute este arquivo no SQL Editor do Supabase.
--
-- IMPORTANTE:
-- Estas políticas permitem CRUD público usando a publishable key.
-- Isso é aceitável apenas para uma aplicação experimental/controlada.
-- Não use estas políticas em um sistema real com dados sensíveis.

create table if not exists public.tarefas (
  id bigint generated by default as identity primary key,
  titulo text not null check (char_length(trim(titulo)) > 0),
  descricao text,
  status text not null default 'pendente'
    check (status in ('pendente', 'concluida')),
  data_criacao timestamptz not null default now()
);

alter table public.tarefas enable row level security;

grant select, insert, update, delete on table public.tarefas to anon;
grant usage, select on sequence public.tarefas_id_seq to anon;

drop policy if exists "experimento_select_tarefas" on public.tarefas;
drop policy if exists "experimento_insert_tarefas" on public.tarefas;
drop policy if exists "experimento_update_tarefas" on public.tarefas;
drop policy if exists "experimento_delete_tarefas" on public.tarefas;

create policy "experimento_select_tarefas"
on public.tarefas
for select
to anon
using (true);

create policy "experimento_insert_tarefas"
on public.tarefas
for insert
to anon
with check (true);

create policy "experimento_update_tarefas"
on public.tarefas
for update
to anon
using (true)
with check (true);

create policy "experimento_delete_tarefas"
on public.tarefas
for delete
to anon
using (true);
